### ISSUE TITLE
Python 3.10 problem with uvloop == "0.15.0"

### ISSUE THREAD

**Issue by incognico** [sqproxy/sqproxy#112]
Theres a peoblem with Python 3.10 and uvloop 0.15.0.

```
Dec 15 14:01:32 twlz systemd[1]: Started sqproxy - Offloading Source Engine query packets (A2S).
Dec 15 14:01:33 twlz sqproxy[343689]: Traceback (most recent call last):
Dec 15 14:01:33 twlz sqproxy[343689]:   File "/usr/bin/sqproxy", line 8, in <module>
Dec 15 14:01:33 twlz sqproxy[343689]:     sys.exit(sqproxy())
Dec 15 14:01:33 twlz sqproxy[343689]:   File "/usr/lib/python3.10/site-packages/click/core.py", line 829, in __call__
Dec 15 14:01:33 twlz sqproxy[343689]:     return self.main(*args, **kwargs)
Dec 15 14:01:33 twlz sqproxy[343689]:   File "/usr/lib/python3.10/site-packages/click/core.py", line 782, in main
Dec 15 14:01:33 twlz sqproxy[343689]:     rv = self.invoke(ctx)
Dec 15 14:01:33 twlz sqproxy[343689]:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
Dec 15 14:01:33 twlz sqproxy[343689]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Dec 15 14:01:33 twlz sqproxy[343689]:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
Dec 15 14:01:33 twlz sqproxy[343689]:     return ctx.invoke(self.callback, **ctx.params)
Dec 15 14:01:33 twlz sqproxy[343689]:   File "/usr/lib/python3.10/site-packages/click/core.py", line 610, in invoke
Dec 15 14:01:33 twlz sqproxy[343689]:     return callback(*args, **kwargs)
Dec 15 14:01:33 twlz sqproxy[343689]:   File "/usr/lib/python3.10/site-packages/source_query_proxy/cli.py", line 12, in run
Dec 15 14:01:33 twlz sqproxy[343689]:     from .__main__ import run
Dec 15 14:01:33 twlz sqproxy[343689]:   File "/usr/lib/python3.10/site-packages/source_query_proxy/__main__.py", line 5, in <module>
Dec 15 14:01:33 twlz sqproxy[343689]:     import uvloop
Dec 15 14:01:33 twlz sqproxy[343689]:   File "/usr/lib/python3.10/site-packages/uvloop/__init__.py", line 7, in <module>
Dec 15 14:01:33 twlz sqproxy[343689]:     from .loop import Loop as __BaseLoop  # NOQA
Dec 15 14:01:33 twlz sqproxy[343689]: ImportError: /usr/lib/python3.10/site-packages/uvloop/loop.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```

`undefined symbol: _PyGen_Send`. See https://github.com/MagicStack/uvloop/issues/417

uvloop 0.16.0 seems to have this fixed (tho I have not verified that) but as the version is fixed to ==0.15.0 in sqproxy it currently won't work with python >=3.10.

**Comment by spumer** [comment]
Fixed in 2.1.1

https://github.com/sqproxy/sqproxy/releases/tag/v2.1.1

Available on pypi
