### ISSUE TITLE
eBPF compilation error: Failed to compile BPF module

### ISSUE THREAD

**Issue by McDonaldsBigMac** [sqproxy/sqproxy#115]
Hello, I have the following error when I enable eBPF redirection in 00-globals.yaml.

```
root@user:/home# sqproxy run
2022-04-05 13:08:15,917 [WARNING] [pyroute2] Beware of the coming changes in the project packaging
2022-04-05 13:08:15,918 [WARNING] [pyroute2] https://github.com/svinota/pyroute2/discussions/786
2022-04-05 13:08:15,929 [INFO] [sqproxy.config] Found config: /etc/sqproxy/conf.d/00-globals.yaml
2022-04-05 13:08:15,940 [INFO] [sqproxy.config] Found config: /etc/sqproxy/conf.d/01-servers.yaml
2022-04-05 13:08:15,943 [INFO] [sqproxy] eBPF redirection enabled
2022-04-05 13:08:15,944 [INFO] [sqproxy] Wait all proxies to be ready ...
2022-04-05 13:08:15,945 [INFO] [Jailbreak] Binding ...
2022-04-05 13:08:15,952 [INFO] [Jailbreak] Binding ... done!
2022-04-05 13:08:15,952 [INFO] [Jailbreak] Listen for client requests ...
2022-04-05 13:08:15,978 [INFO] [sqproxy] Wait all proxies to be ready ... Done!
2022-04-05 13:08:15,979 [WARNING] [pyroute2.ipdb.main] Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
2022-04-05 13:08:15,986 [INFO] [source_query_proxy.epbf] Run ['sqredirect', '-p', 'xxx.xxx.xxx.xxx:27015:27815', '-i', 'enp1s0']
2022-04-05 13:08:16,206 [WARNING] [pyroute2.ipdb.main] Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
2022-04-05 13:08:16,215 [INFO] [main] Building eBPF program ..., cflags=['-include', 'utils.h', '-DUSE_IPPORT_KEY']
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:41:9: warning: '__HAVE_BUILTIN_BSWAP32__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP32__
        ^
<command line>:4:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP32__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:42:9: warning: '__HAVE_BUILTIN_BSWAP64__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP64__
        ^
<command line>:5:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP64__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:43:9: warning: '__HAVE_BUILTIN_BSWAP16__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP16__
        ^
<command line>:3:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP16__ 1
        ^
In file included from /virtual/main.c:3:
include/linux/bpf.h:214:35: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_timer'
                memset(dst + map->timer_off, 0, sizeof(struct bpf_timer));
                                                ^     ~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:214:49: note: forward declaration of 'struct bpf_timer'
                memset(dst + map->timer_off, 0, sizeof(struct bpf_timer));
                                                              ^
include/linux/bpf.h:228:10: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_timer'
                t_sz = sizeof(struct bpf_timer);
                       ^     ~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:228:24: note: forward declaration of 'struct bpf_timer'
                t_sz = sizeof(struct bpf_timer);
                                     ^
include/linux/bpf.h:547:26: error: use of undeclared identifier 'BPF_PSEUDO_FUNC'
               insn->src_reg == BPF_PSEUDO_FUNC;
                                ^
include/linux/bpf.h:1021:21: error: field has incomplete type 'enum bpf_link_type'
        enum bpf_link_type type;
                           ^
include/linux/bpf.h:1021:7: note: forward declaration of 'enum bpf_link_type'
        enum bpf_link_type type;
             ^
include/linux/bpf.h:1035:17: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                              struct bpf_link_info *info);
                                     ^
include/linux/bpf.h:1569:12: warning: declaration of 'union bpf_iter_link_info' will not be visible outside of this function [-Wvisibility]
                                        union bpf_iter_link_info *linfo,
                                              ^
include/linux/bpf.h:1575:14: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                                         struct bpf_link_info *info);
                                                ^
include/linux/bpf.h:1624:12: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                                struct bpf_link_info *info);
                                       ^
include/linux/bpf.h:1792:59: warning: declaration of 'struct bpf_core_relo' will not be visible outside of this function [-Wvisibility]
int bpf_core_apply(struct bpf_core_ctx *ctx, const struct bpf_core_relo *relo,
                                                          ^
8 warnings and 4 errors generated.
Traceback (most recent call last):
  File "/usr/local/bin/sqredirect", line 8, in <module>
    sys.exit(sqredirect())
  File "/usr/local/lib/python3.8/dist-packages/sqredirect/redirect.py", line 342, in sqredirect
    main(args.ports, args.interface)
  File "/usr/local/lib/python3.8/dist-packages/sqredirect/redirect.py", line 152, in main
    bpf = BPF(src_file="redirect.c", cflags=cflags, debug=0)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 347, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module b'redirect.c'
2022-04-05 13:08:18,907 [ERROR] [source_query_proxy.epbf] eBPF redirection exit with code None
NoneType: None
Traceback (most recent call last):
  File "/usr/local/bin/sqproxy", line 8, in <module>
    sys.exit(sqproxy())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/source_query_proxy/cli.py", line 14, in run
    run()
  File "/usr/local/lib/python3.8/dist-packages/pid/decorator.py", line 14, in decorator
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/source_query_proxy/__main__.py", line 19, in run
    asyncio.run(_run_servers())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.8/dist-packages/source_query_proxy/__main__.py", line 50, in _run_servers
    await asyncio.gather(*futures)
  File "/usr/local/lib/python3.8/dist-packages/source_query_proxy/epbf.py", line 96, in run_ebpf_redirection
    raise RuntimeError
RuntimeError
```
I am on Ubuntu 20.04 LTS. What can I do to fix this error?

**Comment by spumer** [comment]
Please provide some info:

Kernel version: `uname -r`
BCC Tools version: `python3 -c 'import bcc; print(bcc.__version__)'`

**Comment by McDonaldsBigMac** [comment]
Outputs are respectively:
`5.17.0-1.2-liquorix-amd64`
`0.12.0`

**Comment by spumer** [comment]
Looks like you have old bcc and new kernel

You can check https://github.com/iovisor/bcc/releases to find BCC versions which support your kernel.

Latest (now 0.24) support up to 5.16.

So, you need use older kernel and build bcc from sources to use latest version. I think you install bcc via apt and packages updated for Ubuntu too late.
