### ISSUE TITLE
Gmod Server Remote Server IP OSError: could not bind to local_addr ('3.38.94.228', 27816)

### ISSUE THREAD

**Issue by REFIRSER2** [sqproxy/sqproxy#117]
now debug error on linux this.
may i need to open the gmod server on local ip and linux?

**Comment by spumer** [comment]
Please show me your config file

**Comment by REFIRSER2** [comment]
conf.d/00-globals.yaml config file.

# Defaults for each server in `servers` section
# Any of these `values` can be overridden locally:
# in local `defaults` section
# in `servers` section
defaults:
  # True - defaults will be applied for each NEXT config file in conf.d directory
  # False - applied only for current file
  # conf.d/ files read sequentially by alphabetical order
  # we recommend start config names with sequential value: 00-globals.yaml, 01-game1.yaml, 02-game2.yaml
  __global__: True
  network:
    # Real game server IP address
    server_ip: '3.38.94.228'
    # IP address for listening incoming queries
    # by default is equal to server_ip, can be omitted (null) or equal to '0.0.0.0'
    bind_ip: null
    # Real game server PORT (respect to server_ip)
    server_port: 0  # don't set in globals, only for doc here
    # PORT for listening incoming queries (respect to bind_ip)
    # by default first available port will be used
    # can be omitted (null) or specified; zero (0) is equal to first available port
    bind_port: 0
    # False (default) - queries from `server_port` will be redirected to `bind_port`
    # only for auto-ebpf handling, for more info see `ebpf` section below
    # True - disable redirection (useful for just proxying and debug purposes)
    ebpf_no_redirect: false

  # Some games have integrated ddos protection
  # and can ban source ip:port for often queries
  # To prevent banning increase cache lifetime(s)

  # How often update A2S_INFO data
  a2s_info_cache_lifetime: 5
  # How often update A2S_RULES data
  a2s_rules_cache_lifetime: 5
  # How often update A2S_PLAYERS data
  a2s_players_cache_lifetime: 1


   # How long wait a2s response
  # can be superseded by a2s_*_cache_lifetime option
  # cause we choose max(a2s_response_timeout, a2s_*_cache_lifetime)
  # This option protect you in situation
  # when server respond longer than your a2s_*_cache_lifetime
  a2s_response_timeout: 1

  # False (default) - no action, A2S_RULES will work
  # True - don't update A2S_RULES cache
  # This will be helpful for HLDS servers which protocol is different
  # But be careful, you also need disable redirection for A2S_RULES packets
  # see the IS_QUERY_REQUEST_PACKET in https://github.com/spumer/source-query-proxy-kernel-module/blob/master/src-ebpf/utils.h
  # CS:GO also has broken A2S_RULES, but fix available at https://forums.alliedmods.net/showthread.php?t=236521
  no_a2s_rules: false


# servers sections is required and can't be empty
# it can be filled by other .yaml files
# See 01-dummy-game.yaml
servers:


# Automatically run eBPF redirection
ebpf:
  # Install any release of SQRedirect
  # https://github.com/sqproxy/sqredirect/releases
  # If you want run it without root privileges, see: https://github.com/sqproxy/sqredirect#non-root-running
  # and make sure executable prepended with 'sudo':
  #   executable:
  #     - 'sudo'
  #     - 'sqredirect'
  enabled: True
  executable: 'sqredirect'

**Comment by REFIRSER2** [comment]
i need to open the proxy computer local computer?
now i'm run the proxy server on linux computer and open the gmod server on windows computer.
and i input the server ip by windows computer ip.

**Comment by REFIRSER2** [comment]
this is error log.

ubuntu@ip-172-31-12-163:~$ sqproxy run
2022-09-18 13:06:38,502 [WARNING] [pyroute2] Beware of the coming changes in the project packaging
2022-09-18 13:06:38,502 [WARNING] [pyroute2] https://github.com/svinota/pyroute2/discussions/786
2022-09-18 13:06:38,536 [INFO] [sqproxy.config] Found config: conf.d/00-globals.yaml
2022-09-18 13:06:38,541 [INFO] [sqproxy.config] Found config: conf.d/01-gmod.yaml
2022-09-18 13:06:38,543 [INFO] [sqproxy] eBPF redirection enabled
2022-09-18 13:06:38,543 [INFO] [sqproxy] Wait all proxies to be ready ...
2022-09-18 13:06:38,545 [INFO] [resident] Binding ... 
2022-09-18 13:06:38,547 [ERROR] [resident] Task unexpectedly completed
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 3073, in uvloop.loop.Loop.create_datagram_endpoint
  File "uvloop/handles/udp.pyx", line 118, in uvloop.loop.UDPTransport._bind
OSError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/source_query_proxy/proxy.py", line 80, in listen_client_requests
    async with (await self.bind(self.listen_addr)) as listening:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/source_query_proxy/transport.py", line 198, in bind
    transport, protocol = await loop.create_datagram_endpoint(
  File "uvloop/loop.pyx", line 3086, in create_datagram_endpoint
OSError: could not bind to local_addr ('3.38.94.228', 27815)
