### ISSUE TITLE
error: Operation not permitted

### ISSUE THREAD

**Issue by that-is-not-great** [sqproxy/sqproxy#127]
```
$ uname -r
5.4.0-187-generic
$ python3 -c 'import bcc; print(bcc.__version__)'
0.12.0
$ python --version
Python 3.8.10
```

I installed 
`python -m pip install sqredirect` 
`pip install source-query-proxy==2.5.0`
`sudo apt-get install bpfcc-tools linux-headers-$(uname -r)`

cs2 is non-root user. I followed the guide "Non-root running" and did all steps

```
$ sudo cat /etc/sudoers.d/network
%network ALL=(root) NOPASSWD: /usr/local/bin/sqredirect
$ groups
cs2 sudo network
```

```
$ sqproxy run
2024-09-05 21:40:26,914 [INFO] [sqproxy.config] Confdir not found: /etc/sqproxy/conf.d
2024-09-05 21:40:26,914 [INFO] [sqproxy.config] Found config: conf.d/00-globals.yaml
2024-09-05 21:40:26,922 [INFO] [sqproxy.config] Found config: conf.d/01-hlds-game.yaml
2024-09-05 21:40:26,925 [INFO] [sqproxy] eBPF redirection enabled
2024-09-05 21:40:26,925 [INFO] [sqproxy] Wait all proxies to be ready ...
2024-09-05 21:40:26,926 [INFO] [HLDS-Server] Binding (('xxx', 30015)) ... 
2024-09-05 21:40:26,930 [INFO] [HLDS-Server] Binding (('xxx', 30015)) ... done!
2024-09-05 21:40:26,930 [INFO] [HLDS-Server] Listen for client requests on ('xxx', 30015) ...
2024-09-05 21:40:26,951 [INFO] [HLDS-Server] Server UP now
2024-09-05 21:40:26,952 [INFO] [sqproxy] Wait all proxies to be ready ... Done!
2024-09-05 21:40:26,952 [WARNING] [pyroute2.ipdb.main] Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
2024-09-05 21:40:26,952 [WARNING] [pyroute2.ipdb.main] To remove this DeprecationWarning exception, start IPDB(deprecation_warning=False, ...)
2024-09-05 21:40:26,962 [INFO] [source_query_proxy.epbf] Run ['sqredirect', '-p', 'xxx:27015:30015', '-i', 'ens3']
2024-09-05 21:40:27,246 [WARNING] [pyroute2.ipdb.main] Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
2024-09-05 21:40:27,246 [WARNING] [pyroute2.ipdb.main] To remove this DeprecationWarning exception, start IPDB(deprecation_warning=False, ...)
2024-09-05 21:40:27,256 [INFO] [main] Building eBPF program ..., cflags=['-include', 'utils.h', '-DUSE_IPPORT_KEY']
could not open bpf map: addr_proxy2gameserver_port, error: Operation not permitted
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/cs2/.local/bin/sqredirect", line 8, in <module>
    sys.exit(sqredirect())
  File "/home/cs2/.local/lib/python3.8/site-packages/sqredirect/redirect.py", line 342, in sqredirect
    main(args.ports, args.interface)
  File "/home/cs2/.local/lib/python3.8/site-packages/sqredirect/redirect.py", line 152, in main
    bpf = BPF(src_file="redirect.c", cflags=cflags, debug=0)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 347, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module b'redirect.c'
2024-09-05 21:40:31,324 [ERROR] [source_query_proxy.epbf] eBPF redirection exit with code None
NoneType: None
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/cs2/.local/bin/sqproxy", line 8, in <module>
    sys.exit(sqproxy())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/cs2/.local/lib/python3.8/site-packages/source_query_proxy/cli.py", line 14, in run
    run()
  File "/home/cs2/.local/lib/python3.8/site-packages/pid/decorator.py", line 14, in decorator
    return func(*func_args, **func_kwargs)
  File "/home/cs2/.local/lib/python3.8/site-packages/source_query_proxy/__main__.py", line 24, in run
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/cs2/.local/lib/python3.8/site-packages/source_query_proxy/__main__.py", line 28, in main
    await _run_servers()
  File "/home/cs2/.local/lib/python3.8/site-packages/source_query_proxy/__main__.py", line 59, in _run_servers
    await asyncio.gather(*futures)
  File "/home/cs2/.local/lib/python3.8/site-packages/source_query_proxy/epbf.py", line 96, in run_ebpf_redirection
    raise RuntimeError
RuntimeError
```

```
$ sudo sqproxy run
Traceback (most recent call last):
  File "/home/cs2/.local/bin/sqproxy", line 5, in <module>
    from source_query_proxy.cli import sqproxy
ModuleNotFoundError: No module named 'source_query_proxy'
```

**Comment by that-is-not-great** [comment]
I installed all again with root, and its running now, but the server is not visible in the game browser nor in favorites

```
root@XXX:~# sqproxy run
2024-09-05 22:27:26,499 [INFO] [sqproxy.config] Found config: /etc/sqproxy/conf.d/00-globals.yaml
2024-09-05 22:27:26,508 [INFO] [sqproxy.config] Found config: /etc/sqproxy/conf.d/01-hlds-game.yaml
2024-09-05 22:27:26,510 [INFO] [sqproxy.config] Confdir not found: /root/conf.d
2024-09-05 22:27:26,511 [INFO] [sqproxy] eBPF redirection enabled
2024-09-05 22:27:26,511 [INFO] [sqproxy] Wait all proxies to be ready ...
2024-09-05 22:27:26,512 [INFO] [HLDS-Server] Binding (('xxx', 30015)) ... 
2024-09-05 22:27:26,516 [INFO] [HLDS-Server] Binding (('xxx', 30015)) ... done!
2024-09-05 22:27:26,516 [INFO] [HLDS-Server] Listen for client requests on ('xxx', 30015) ...
2024-09-05 22:27:26,520 [INFO] [HLDS-Server] Server UP now
2024-09-05 22:27:26,523 [INFO] [sqproxy] Wait all proxies to be ready ... Done!
2024-09-05 22:27:26,523 [WARNING] [pyroute2.ipdb.main] Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
2024-09-05 22:27:26,523 [WARNING] [pyroute2.ipdb.main] To remove this DeprecationWarning exception, start IPDB(deprecation_warning=False, ...)
2024-09-05 22:27:26,533 [INFO] [source_query_proxy.epbf] Run ['sqredirect', '-p', 'xxx 27015:30015', '-i', 'ens3']
2024-09-05 22:27:26,867 [WARNING] [pyroute2.ipdb.main] Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
2024-09-05 22:27:26,867 [WARNING] [pyroute2.ipdb.main] To remove this DeprecationWarning exception, start IPDB(deprecation_warning=False, ...)
2024-09-05 22:27:26,878 [INFO] [main] Building eBPF program ..., cflags=['-include', 'utils.h', '-DUSE_IPPORT_KEY']
2024-09-05 22:27:31,288 [INFO] [main] Attach eBPF program to interface ...
2024-09-05 22:27:31,289 [DEBUG] [main] Setup incoming hook (2) (b'incoming')
2024-09-05 22:27:31,295 [DEBUG] [main] Setup outgoing hook (2) (b'outgoing')
2024-09-05 22:27:31,300 [INFO] [main] Running ...
```

what could be the issue?

**Comment by that-is-not-great** [comment]
the port 30015 must be open.

i made a fresh try for non-root but now there is some issue with bcc

`sudo apt-get install bpfcc-tools linux-headers-$(uname -r)`

```
bpfcc-tools is already the newest version (0.12.0-2).
linux-headers-5.15.0-119-generic is already the newest version (5.15.0-119.129~20.04.1).
```

```
$ python -c 'import bcc; print(bcc.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'bcc'
$ python3 -c 'import bcc; print(bcc.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'bcc'
$ python --version
Python 3.10.3
```

```
$ sqproxy run
2024-09-06 01:14:21,078 [INFO] [sqproxy.config] Found config: /etc/sqproxy/conf.d/00-globals.yaml
2024-09-06 01:14:21,085 [INFO] [sqproxy.config] Found config: /etc/sqproxy/conf.d/01-hlds-game.yaml
2024-09-06 01:14:21,086 [INFO] [sqproxy.config] Confdir not found: /home/cs/conf.d
2024-09-06 01:14:21,087 [INFO] [sqproxy] eBPF redirection enabled
2024-09-06 01:14:21,087 [INFO] [sqproxy] Wait all proxies to be ready ...
2024-09-06 01:14:21,087 [INFO] [HLDS-Server] Binding (('xxx', 30015)) ... 
2024-09-06 01:14:21,090 [INFO] [HLDS-Server] Binding (('xxx', 30015)) ... done!
2024-09-06 01:14:21,090 [INFO] [HLDS-Server] Listen for client requests on ('xxx', 30015) ...
2024-09-06 01:14:21,093 [INFO] [HLDS-Server] Server UP now
2024-09-06 01:14:21,094 [INFO] [sqproxy] Wait all proxies to be ready ... Done!
2024-09-06 01:14:21,094 [WARNING] [pyroute2.ipdb.main] Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
2024-09-06 01:14:21,094 [WARNING] [pyroute2.ipdb.main] To remove this DeprecationWarning exception, start IPDB(deprecation_warning=False, ...)
2024-09-06 01:14:21,102 [INFO] [source_query_proxy.epbf] Run ['sqredirect', '-p', 'xxx:27015:30015', '-i', 'enp4s0']
Traceback (most recent call last):
  File "/home/cs/.pyenv/versions/3.10.3/bin/sqredirect", line 5, in <module>
    from sqredirect.redirect import sqredirect
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/site-packages/sqredirect/redirect.py", line 14, in <module>
    from bcc import BPF
ModuleNotFoundError: No module named 'bcc'
2024-09-06 01:14:21,152 [ERROR] [source_query_proxy.epbf] eBPF redirection exit with code 1
NoneType: None
Traceback (most recent call last):
  File "/home/cs/.pyenv/versions/3.10.3/bin/sqproxy", line 8, in <module>
    sys.exit(sqproxy())
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/site-packages/source_query_proxy/cli.py", line 14, in run
    run()
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/site-packages/pid/decorator.py", line 14, in decorator
    return func(*func_args, **func_kwargs)
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/site-packages/source_query_proxy/__main__.py", line 24, in run
    asyncio.run(main())
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/site-packages/source_query_proxy/__main__.py", line 28, in main
    await _run_servers()
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/site-packages/source_query_proxy/__main__.py", line 59, in _run_servers
    await asyncio.gather(*futures)
  File "/home/cs/.pyenv/versions/3.10.3/lib/python3.10/site-packages/source_query_proxy/epbf.py", line 96, in run_ebpf_redirection
    raise RuntimeError
RuntimeError
```

edit: built from source now

**Comment by spumer** [comment]
>ModuleNotFoundError: No module named 'bcc'

When you build from sources 
https://github.com/iovisor/bcc/blob/master/INSTALL.md#install-and-compile-bcc-1

Pay attention to line `cmake -DPYTHON_CMD=python3 .. # build python3 binding`

Here `python3` should point to your python3 installation, where bcc module will be placed. And this python3 should be used or inherited (e.g by venv) to run 


>the port 30015 must be open.

Yeah, if you have firewall on the same machine

**Comment by that-is-not-great** [comment]
now bcc is installed,

 but still `could not open bpf map: addr_proxy2gameserver_port, error: Operation not permitted`
 its only working as  `sudo sqproxy run`. I did all steps for non-root twice. how can I investigate the issue?
 
 same as here https://github.com/sqproxy/sqredirect/issues/8

**Comment by spumer** [comment]
Can you show me `ebpf` section from your .yaml config?

It should be looks like this:

```
ebpf:
  enabled: true
  executable:
    - 'sudo'
    - 'sqredirect'
```

**Comment by that-is-not-great** [comment]
thank you, it is commented in the yaml, it was not clear to me via docs! now its working perfectly. thank you so so much for this!

PS. where does the query ping come from? it is not `A2A_PING` ?

**Comment by spumer** [comment]
Ping it's a latency between A2S_* request-responses.

A2A_PING is legacy and not used
