### ISSUE TITLE
plz help me -> sqproxy run  error occurred...

### ISSUE THREAD

**Issue by crab-hash** [sqproxy/sqproxy#128]
note:
uname -r;python3 -c 'import bcc; print(bcc.__version__)'
5.15.0-124-generic
0.18.0

sudo apt-get install bpfcc-tools linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
bpfcc-tools is already the newest version (0.18.0+ds-2).
linux-headers-5.15.0-124-generic is already the newest version (5.15.0-124.134).
The following packages were automatically installed and are no longer required:
  libjs-sphinxdoc libjs-underscore libpython3-dev libpython3.10-dev python3-dev python3-wheel python3.10-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

uname -a
Linux nanfang 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

console info:

sqproxy run
2024-11-10 07:40:14,256 [INFO] [sqproxy.config] Found config: /etc/sqproxy/conf.d/00-globals.yaml
2024-11-10 07:40:14,259 [INFO] [sqproxy.config] Found config: /etc/sqproxy/conf.d/01-game1.yaml
2024-11-10 07:40:14,260 [INFO] [sqproxy.config] Confdir not found: /root/conf.d
2024-11-10 07:40:14,260 [INFO] [sqproxy] eBPF redirection enabled
2024-11-10 07:40:14,260 [INFO] [sqproxy] Wait all proxies to be ready ...
2024-11-10 07:40:14,260 [INFO] [test01] Binding (('192.168.8.173', 4444)) ...
2024-11-10 07:40:14,262 [INFO] [test01] Binding (('192.168.8.173', 4444)) ... done!
2024-11-10 07:40:14,262 [INFO] [test01] Listen for client requests on ('192.168.8.173', 4444) ...
2024-11-10 07:40:19,261 [WARNING] [test01] Graceful period for wait ready exceeded. Skip waiting
2024-11-10 07:40:19,261 [INFO] [sqproxy] Wait all proxies to be ready ... Done!
2024-11-10 07:40:19,261 [WARNING] [pyroute2.ipdb.main] Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
2024-11-10 07:40:19,262 [WARNING] [pyroute2.ipdb.main] To remove this DeprecationWarning exception, start IPDB(deprecation_warning=False, ...)
2024-11-10 07:40:19,267 [INFO] [source_query_proxy.epbf] Run ['sqredirect', '-p', '192.168.8.173:3333:4444', '-i', 'ens160']
2024-11-10 07:40:19,414 [WARNING] [pyroute2.ipdb.main] Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
2024-11-10 07:40:19,414 [WARNING] [pyroute2.ipdb.main] To remove this DeprecationWarning exception, start IPDB(deprecation_warning=False, ...)
2024-11-10 07:40:19,420 [INFO] [main] Building eBPF program ..., cflags=['-include', 'utils.h', '-DUSE_IPPORT_KEY']
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:5:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:41:9: warning: '__HAVE_BUILTIN_BSWAP32__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP32__
        ^
<command line>:4:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP32__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:5:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:42:9: warning: '__HAVE_BUILTIN_BSWAP64__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP64__
        ^
<command line>:5:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP64__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:5:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:43:9: warning: '__HAVE_BUILTIN_BSWAP16__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP16__
        ^
<command line>:3:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP16__ 1
        ^
In file included from /virtual/main.c:3:
include/linux/bpf.h:220:35: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_timer'
                memset(dst + map->timer_off, 0, sizeof(struct bpf_timer));
                                                ^     ~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:220:49: note: forward declaration of 'struct bpf_timer'
                memset(dst + map->timer_off, 0, sizeof(struct bpf_timer));
                                                              ^
include/linux/bpf.h:234:10: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_timer'
                t_sz = sizeof(struct bpf_timer);
                       ^     ~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:234:24: note: forward declaration of 'struct bpf_timer'
                t_sz = sizeof(struct bpf_timer);
                                     ^
include/linux/bpf.h:553:26: error: use of undeclared identifier 'BPF_PSEUDO_FUNC'
               insn->src_reg == BPF_PSEUDO_FUNC;
                                ^
In file included from /virtual/main.c:7:
In file included from include/linux/udp.h:16:
In file included from include/net/inet_sock.h:22:
In file included from include/net/sock.h:59:
include/linux/filter.h:1525:44: error: use of undeclared identifier 'BPF_F_BROADCAST'; did you mean 'IFF_BROADCAST'?
        if (unlikely(!ri->tgt_value) && !(flags & BPF_F_BROADCAST)) {
                                                  ^~~~~~~~~~~~~~~
                                                  IFF_BROADCAST
include/uapi/linux/if.h:86:2: note: 'IFF_BROADCAST' declared here
        IFF_BROADCAST                   = 1<<1,  /* volatile */
        ^
In file included from /virtual/main.c:7:
In file included from include/linux/udp.h:16:
In file included from include/net/inet_sock.h:22:
In file included from include/net/sock.h:59:
include/linux/filter.h:1540:14: error: use of undeclared identifier 'BPF_F_BROADCAST'; did you mean 'IFF_BROADCAST'?
        if (flags & BPF_F_BROADCAST) {
                    ^~~~~~~~~~~~~~~
                    IFF_BROADCAST
include/uapi/linux/if.h:86:2: note: 'IFF_BROADCAST' declared here
        IFF_BROADCAST                   = 1<<1,  /* volatile */
        ^
3 warnings and 5 errors generated.
Traceback (most recent call last):
  File "/usr/local/bin/sqredirect", line 8, in <module>
    sys.exit(sqredirect())
  File "/usr/local/lib/python3.10/dist-packages/sqredirect/redirect.py", line 342, in sqredirect
    main(args.ports, args.interface)
  File "/usr/local/lib/python3.10/dist-packages/sqredirect/redirect.py", line 152, in main
    bpf = BPF(src_file="redirect.c", cflags=cflags, debug=0)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 364, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module b'redirect.c'
2024-11-10 07:40:20,787 [ERROR] [source_query_proxy.epbf] eBPF redirection exit with code 1
NoneType: None
Traceback (most recent call last):
  File "/usr/local/bin/sqproxy", line 8, in <module>
    sys.exit(sqproxy())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/source_query_proxy/cli.py", line 14, in run
    run()
  File "/usr/local/lib/python3.10/dist-packages/pid/decorator.py", line 14, in decorator
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/source_query_proxy/__main__.py", line 24, in run
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/source_query_proxy/__main__.py", line 28, in main
    await _run_servers()
  File "/usr/local/lib/python3.10/dist-packages/source_query_proxy/__main__.py", line 59, in _run_servers
    await asyncio.gather(*futures)
  File "/usr/local/lib/python3.10/dist-packages/source_query_proxy/epbf.py", line 96, in run_ebpf_redirection
    raise RuntimeError
RuntimeError

**Comment by spumer** [comment]
@crab-hash 
issue resolved?

**Comment by crab-hash** [comment]
hello spumer!
I managed to get it to work, but the flood flooded my server, and how do I verify that the program is running?
![5](https://github.com/user-attachments/assets/d1aaacbe-1347-48c8-a5c5-8225ff6403cf)

**Comment by spumer** [comment]
1. Server respond to queries
2. Play time in detailed server info is updated with the same period as specified in the settings "a2s_players_cache_lifetime"

**Comment by crab-hash** [comment]
I set the option "no_a2s_rules" to true and use the Steam Server Browser and I don't see rules there. Seems to verify that it is working

![1](https://github.com/user-attachments/assets/edd94bde-879e-44bb-9941-0131c78467df)

**Comment by crab-hash** [comment]
[00-globals.yaml.txt](https://github.com/user-attachments/files/17714848/00-globals.yaml.txt)

this is my globals.yaml

**Comment by spumer** [comment]
~~Please provide info about your server:~~
~~**Game:** left4dead2/css/csgo/cs2/...~~

I see it's left4dead2.
You must use `no_a2s_rules=false`, and A2S_RULES should works fine

---
```
  # False (default) - no action, A2S_RULES will work
  # True - don't update A2S_RULES cache
```

So, no_a2s_rules=true mean "ignore a2s_rules requests".
But additional action required to disable catching this requests. It's not obvious currently and discribed in config example:

https://github.com/sqproxy/sqproxy/blob/172ba6de7eb55e4df3bca62b0ecccc68503cb88d/examples/conf.d/00-globals.yaml#L52

But for left4dead2 it's not needed and please use default value: `no_a2s_rules=false`

**Comment by crab-hash** [comment]
![1](https://github.com/user-attachments/assets/eac0c01e-8ade-4a27-9a49-9b46ceb50f4b)

Ok, I restored the default value to false.
Seeing these after restarting the program, is this working?

**Comment by spumer** [comment]
Looks like gameserver does not sent Rules Response to `sqproxy`. It's ok when sqproxy started, but not okay for 5 min or more

Please post output with debug logs enabled.
`SQPROXY_LOGLEVEL=DEBUG sqproxy run`

**Comment by crab-hash** [comment]
here，got that pics
![1](https://github.com/user-attachments/assets/6a2015b8-33b1-4ef9-9687-a6051f5c2423)

![2](https://github.com/user-attachments/assets/af217bce-8bd1-4141-baa1-eebeff72916c)

**Comment by spumer** [comment]
I do not see `update-rules` logs. Redirect output to file `SQPROXY_LOGLEVEL=DEBUG sqproxy run | tee console.log` and attach it here pls

Looks like no_a2s_rules are still True?

**Comment by crab-hash** [comment]
[00-globals.yaml.txt](https://github.com/user-attachments/files/17769632/00-globals.yaml.txt)
[01-game1.yaml.txt](https://github.com/user-attachments/files/17769633/01-game1.yaml.txt)
[console.log.txt](https://github.com/user-attachments/files/17769634/console.log.txt)

Well, I've put the file here, squmer
